### PR TITLE
Skip failing tests on docker 1.10

### PR DESCRIPTION
**Pull request by edsantiago**
rhbz#1330224 causes failures in docker-1.10 but is fixed
in 1.12 (it was never a problem pre-1.10). The bug will
not be fixed in any RH build of docker-1.10, so let's just
skip it to make CI happy.

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
Uggg, sorry, dunno why github didn't notify me about this.

**Comment by edsantiago** [comment]
Oh, no worries. I thought you were working on an ADEPT-based solution.

**Comment by cevich** [comment]
Nope, been trying to fix the ADEPT and Docker Autotest CI jobs.  Looking at the code here though, I wonder if this isn't a better solution.  Mainly because we can just drop it after 1.10 is no longer anywhere to be seen.

**Comment by cevich** [comment]
Haha! Will you look at that, it's running and not blocking the Jenkins Queue :confounded:

**Comment by cevich** [comment]
CI is happy with this.  ``From 115 tests executed, 110 have passed (pass rate of 95.0%)`` but two of those are ``TestNA``'s (marked as failure by Jenkins) and the start test is green now  :grinning:

**Pull request merged**
