### PR TITLE
Instrumentation: enhanced diagnostic msgs

### PR DESCRIPTION
**Pull request by edsantiago**
...in hopes of figuring out what's causing ADEPT failures.

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
@edsantiago using this for the ADEPT runs or intending to merge the enhancements (test could certainly use them)??

**Comment by edsantiago** [comment]
I'm waiting for ADEPT to finish, then will check in the whitespace fix and any further fine-tuning necessary

**Comment by cevich** [comment]
Gotcha, NP either way.

I've got a risky set of changes queued up for merge into both CI jobs (ADEPT and Docker-Autotest).  They're passing in my devel. env. but no idea if that means they'll work in production.

I'll hold off on merging so you can get what you need here.

**Comment by cevich** [comment]
Ohh it's done....Hrmmm, that ``build/git_path`` failure is on me.  It's suppose to be skipped on Atomic hosts (they're lacking git).  Haven't looked at the other one.

**Comment by cevich** [comment]
...okay, got a fix for that ``git_path`` failure, along with a few others probably.  The CI job wasn't using any ``control.ini`` template.  I pointed it at the default one:

https://github.com/cevich/autotest-docker-enabled-product-testing/blob/master/roles/autotested/templates/control.ini.j2

Staging that change along with others 'till you're done here.

**Comment by edsantiago** [comment]
I don't think these changes are helpful. At least, not helpful enough. Given the failures I'm seeing in dockerignore, the only way to diagnose further is going to be ssh'ing into the failing vm and looking at the docker build dir. I'm flummoxed.

**Comment by cevich** [comment]
> the only way to diagnose further is going to be ssh'ing into the failing vm

Writing you a private e-mail about this...

**Comment by edsantiago** [comment]
Looking into this now. But I don't think this PR should block your fixes to the rest of ADEPT.

**Comment by cevich** [comment]
> Looking into this now. But I don't think this PR should block your fixes to the rest of ADEPT.

My changes affect the ``variables.yml`` content/format and they're risky, may break all jobs (hopefully not).  So Just let me know if you get a VM up you can use, and we can close this PR and then I'll merge my stuff.

**Comment by edsantiago** [comment]
Squashed, force-pushed. I learned what I needed from this. If you think these changes might help in diagnosing future failure, please feel free to merge.

**Pull request closed without merging**
