### PR TITLE
Add supporting class for testing with bash

### PR DESCRIPTION
**Pull request by cevich**
Sometimes we're in a hurry, and just need to toss a quick and
simplistic test using only shell-scripts.  Support this
with a new ``BashSubtest`` class and example implementation
in ``subtests/bashexample/``.

[skip-ci]

### CODE REVIEW

**Comment by cevich** [comment]
**N/B:** Untested, just an early prototype of an idea.

**Comment by edsantiago** [comment]
Obvious first question: how does one script pass state to the next?

**Comment by cevich** [comment]
> Obvious first question: how does one script pass state to the next?

Simple, it's left up to the script author.

This isn't about supporting polished, long-term maintainable tests, it's only providing an extremely low entry-barrier for situations/people where that's helpful.

**Comment by cevich** [comment]
--force push got it actually working with some more sane-logging.

**Comment by cevich** [comment]
**N/B**: To be clear, NONE of the changes from ``FUDGING FOR A PR/CI TEST - DO NOT MERGE`` are going in.  That was just a look-and-feel test.

---

After playing with that ``dummy/test``, it seems alright.  It's easy to copy-paste from the ``bashexample``, and it supports the ini-configuration right out-of-the-box.  IMHO, it's possibly something engineering or an "outsider" would appreciate, for the occasional rattle-trap / quickie-contribution.

**Comment by cevich** [comment]
abandoned, can re-open if ever needed.

**Pull request closed without merging**
