### PR TITLE
New subtest: cp_symlink, tests copying into container

### PR DESCRIPTION
**Pull request by edsantiago**
...especially into a path pointed to by a symlink.
Confirms two CVEs, plus regressions introduced in
the fixing thereof

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
New corner cases in cp. Tested with older docker, with patched version from Giuseppe, and with podman.

**Comment by edsantiago** [comment]
@cevich looks like CI is broken. Any chance of merging this in anyway?

**Comment by cevich** [comment]
I'm totally not surprised.  Ya, one sec let me get that out of the way...

**Pull request merged**
