### PR TITLE
Fix build case + provide repo replace interface

### PR DESCRIPTION
**Pull request by luwensu**
1.Fix the build fails_msg
The commented line is for 'empty_base_image' and another one is based the rhel7 image
2.Provide the repo replace interface
Use two functions to find the Dockerfile's FROM token and replace its value which is what the repo is.
And provide the configuration dockerfile_use_config_repo to control it

Signed-off-by: Time Su <lsu@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
Another big update to https://github.com/luwensu/autotest-docker/pull/1

**Comment by cevich** [comment]
Okay, this is top of my list again, taking a deeper look to see what else needs fixing..

**Comment by cevich** [comment]
Hmmm crap, something horrible happened with indentation.  Not sure if it was my fault or not, but please double-check your editor is not using/replacing spaces with tab character.  Everything should be space character only, with 4-spaces used for one indentation block.  I'll see if I can fix it up quick...

**Comment by cevich** [comment]
@luwensu Okay, I fixed up all the whitespace problems (not sure where they came from).  Then got through fixing most of my bad typos and mistakes :D  Now, all the sub-subtests are running properly (no python errors).  However, most of the 'fancy' sub-subtests are failing and I haven't looked into them yet.  All your stuff is still cool, it's just things I messed up, take a look if you like:

https://github.com/cevich/autotest-docker/compare/luwensu-fix_build_replace_repo

I'll keep hacking on it tomorrow, should probably be able to finish and push this all up.  Thanks a bunch for all your help reviewing and spotting problems!

**Comment by cevich** [comment]
Spent the day tracking down what I thought was a docker bug, turns out ``dockerfile_repo_replace()`` is loosing ``Dockerfile`` contents somehow, investigating, hopefully it's just a silly typo...

**Comment by cevich** [comment]
@luwensu ``re.sub()`` is your friend :smile:  Fixed the method your wrote accidentally truncating the output file.  No worries, everybody makes mistakes :wink:   Many more updates on https://github.com/cevich/autotest-docker/compare/luwensu-fix_build_replace_repo now have the cache test working and only some minor configuration tweaks are needed for the other tests.  Should be able to finish and merge this tomorrow.

**Comment by luwensu** [comment]
@cevich,ah.... sorry , i should do a pylint berfore merged that big PR and also for repo place method, sorry again really as i were not spend much time on it in the few days, some other matters (meetings, activities blahblah )and no excuse, my fault - -.
Okay, i'll clone it to my test machine to have  a test too to see both anything i can help and the changes need figure out, it's my duty, will let you know for what i do. Thanks your big help always :)

**Pull request closed without merging**
