### PR TITLE
(minor): sphinx comment fixes

### PR DESCRIPTION
**Pull request by edsantiago**
- Documented one exception in new failif_not_in()
- Fixed minor spelling/syntax errors in other doc strings

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
Still one instance in need of fixing:

    subtests/docker_cli/dockerinspect/dockerinspect.py
    80:        :raise: throw some exception handling in here

...but it looks like a FIXME that I'm not sure how to FIX :)

**Comment by cevich** [comment]
> why did I not get it in the github email?

Ya, sorry, I edited the comment after remembering that I thought to look up the link and add it but forgot and save the comment but later remembered that I forgot :grin:

**Comment by edsantiago** [comment]
No worries, that explains it perfectly. Thanks; I do appreciate the link.

**Comment by cevich** [comment]
> ...but it looks like a FIXME that I'm not sure how to FIX :)

That test was written by a short-term helper who went back to his regular position.  IIRC, it was decided a long time ago that inspecting files under /var/lib/docker/... isn't completely a safe thing to do.  We chose to do it anyway because at the time there was some container JSON not properly updated in the output from ``inspect`` - IIRC, he filed a bug on this, I think it was about the networking data.  I'd offer to ask the author, but I doubt he'd remember.  Anyway, I'm guessing that's what the silly ``raise`` docstring is relating to - the ``open()``, ``container_path`` access, and that ``HostConfig`` branch is updated.

**Comment by cevich** [comment]
Oh, that is all to say...feel free to nuke that line 80 to make the problem 'go away'.   Though some future l337-hax0R might prefer if my comment above was included into the code :grinning:

**Comment by cevich** [comment]
BTW, I did get a notice e-mail when you opened this PR.  odd.

**Comment by edsantiago** [comment]
Incomplete :raise: line nuked. Also fixed a typo in the previous line. Merging.

**Pull request merged**
